-- MySQL Script generated by MySQL Workbench
-- Sun Feb  3 00:08:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clase` (
  `idClasa` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idClasa`),
  UNIQUE INDEX `idClasa_UNIQUE` (`idClasa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Elevi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Elevi` (
  `idElev` INT NOT NULL AUTO_INCREMENT,
  `numeElev` VARCHAR(30) NOT NULL,
  `orasElev` VARCHAR(25) NOT NULL,
  `sexElev` VARCHAR(5) NOT NULL,
  `tlfElev` VARCHAR(13) NULL,
  `birthdayElev` DATE NOT NULL,
  `Clase_idClasa` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idElev`),
  UNIQUE INDEX `idElev_UNIQUE` (`idElev` ASC) VISIBLE,
  INDEX `fk_Elevi_Clase_idx` (`Clase_idClasa` ASC) VISIBLE,
  CONSTRAINT `fk_Elevi_Clase`
    FOREIGN KEY (`Clase_idClasa`)
    REFERENCES `mydb`.`Clase` (`idClasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cursuri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cursuri` (
  `idCurs` VARCHAR(3) NOT NULL,
  `numeCurs` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCurs`),
  UNIQUE INDEX `idCurs_UNIQUE` (`idCurs` ASC) VISIBLE)
ENGINE = InnoDB;

--
-- Dumping data for table `cursuri`
--

INSERT INTO `cursuri` (`idCurs`, `numeCurs`) VALUES
('BIO', 'Biologie'),
('CHI', 'Chimie'),
('EDA', 'Ed. Antreprenoriala'),
('EDF', 'Ed. Fizica'),
('EDM', 'Ed. Muzicala'),
('EDP', 'Ed. Plastica'),
('EN', 'Lb. Engleza'),
('FIZ', 'Fizica'),
('FR', 'Lb. Franceza'),
('GEO', 'Geografie'),
('INF', 'Informatica'),
('IST', 'Istorie'),
('MAT', 'Matematica'),
('PUR', 'Purtare'),
('REL', 'Religie'),
('RO', 'Lb. Romana'),
('SSU', 'Stiinte Socio-Umane'),
('TIC', 'Teh. Info. si Com.');

-- -----------------------------------------------------
-- Table `mydb`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Note` (
  `idNota` INT NOT NULL AUTO_INCREMENT,
  `Elevi_idElev` INT NOT NULL,
  `Cursuri_idCurs` VARCHAR(3) NOT NULL,
  `nota` INT NULL,
  `teza` INT NULL,
  PRIMARY KEY (`idNota`),
  UNIQUE INDEX `idNota_UNIQUE` (`idNota` ASC) VISIBLE,
  INDEX `fk_Note_Elevi1_idx` (`Elevi_idElev` ASC) VISIBLE,
  INDEX `fk_Note_Cursuri1_idx` (`Cursuri_idCurs` ASC) VISIBLE,
  CONSTRAINT `fk_Note_Elevi1`
    FOREIGN KEY (`Elevi_idElev`)
    REFERENCES `mydb`.`Elevi` (`idElev`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Note_Cursuri1`
    FOREIGN KEY (`Cursuri_idCurs`)
    REFERENCES `mydb`.`Cursuri` (`idCurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Absente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Absente` (
  `idAbsenta` INT NOT NULL AUTO_INCREMENT,
  `Cursuri_idCurs` VARCHAR(3) NOT NULL,
  `Elevi_idElev` INT NOT NULL,
  `dataAbsenta` DATE NOT NULL,
  PRIMARY KEY (`idAbsenta`),
  UNIQUE INDEX `idAbsenta_UNIQUE` (`idAbsenta` ASC) VISIBLE,
  INDEX `fk_Absente_Cursuri1_idx` (`Cursuri_idCurs` ASC) VISIBLE,
  INDEX `fk_Absente_Elevi1_idx` (`Elevi_idElev` ASC) VISIBLE,
  CONSTRAINT `fk_Absente_Cursuri1`
    FOREIGN KEY (`Cursuri_idCurs`)
    REFERENCES `mydb`.`Cursuri` (`idCurs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Absente_Elevi1`
    FOREIGN KEY (`Elevi_idElev`)
    REFERENCES `mydb`.`Elevi` (`idElev`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
